









/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author JIANLUCAPALINI
 */
public class Lanchonete extends javax.swing.JFrame {

    /**
     * Creates new form Lanchonete
     */
    public Lanchonete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        chkBatata1 = new javax.swing.JCheckBox();
        chkBatata2 = new javax.swing.JCheckBox();
        chkBatata4 = new javax.swing.JCheckBox();
        chkBatata3 = new javax.swing.JCheckBox();
        chkBatata5 = new javax.swing.JCheckBox();
        chkBatata6 = new javax.swing.JCheckBox();
        chkBatata7 = new javax.swing.JCheckBox();
        chkBebida3 = new javax.swing.JCheckBox();
        chkBebida1 = new javax.swing.JCheckBox();
        chkBebida2 = new javax.swing.JCheckBox();
        chkBebida4 = new javax.swing.JCheckBox();
        chkBebida5 = new javax.swing.JCheckBox();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        chkBatata9 = new javax.swing.JCheckBox();
        chkBatata10 = new javax.swing.JCheckBox();
        chkBatata8 = new javax.swing.JCheckBox();
        chkBatata11 = new javax.swing.JCheckBox();
        chkBatata12 = new javax.swing.JCheckBox();
        chkBatata14 = new javax.swing.JCheckBox();
        chkBatata13 = new javax.swing.JCheckBox();
        jTextField6 = new javax.swing.JTextField();
        chkBebida6 = new javax.swing.JCheckBox();
        jTextField7 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnPedido = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));

        jPanel2.setBackground(new java.awt.Color(89, 62, 36));

        jTextField1.setBackground(new java.awt.Color(255, 204, 153));
        jTextField1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 153, 0));
        jTextField1.setText("DELIVERY");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(255, 204, 153));
        jTextField2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 153, 0));
        jTextField2.setText("RAIZ & RECHEIO");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(564, 564, 564)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(485, 485, 485)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(669, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        chkBatata1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBatata1.setForeground(new java.awt.Color(0, 0, 0));
        chkBatata1.setText("Batata Recheada de Calabresa - R$ 29,90 ");
        chkBatata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBatata1ActionPerformed(evt);
            }
        });

        chkBatata2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBatata2.setForeground(new java.awt.Color(0, 0, 0));
        chkBatata2.setText("Batata Recheada de Frango e Catupiry - R$ 27,90 ");
        chkBatata2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBatata2ActionPerformed(evt);
            }
        });

        chkBatata4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBatata4.setForeground(new java.awt.Color(0, 0, 0));
        chkBatata4.setText("Batata Recheada de Carne Loka - R$ 32,90 ");
        chkBatata4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBatata4ActionPerformed(evt);
            }
        });

        chkBatata3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBatata3.setForeground(new java.awt.Color(0, 0, 0));
        chkBatata3.setText("Batata Recheada de Bolonhesa - R$ 32,90 ");
        chkBatata3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBatata3ActionPerformed(evt);
            }
        });

        chkBatata5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBatata5.setForeground(new java.awt.Color(0, 0, 0));
        chkBatata5.setText("Batata Recheada de Carne com Cheddar - R$ 32,90 ");
        chkBatata5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBatata5ActionPerformed(evt);
            }
        });

        chkBatata6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBatata6.setForeground(new java.awt.Color(0, 0, 0));
        chkBatata6.setText("Batata Recheada de Bacon com Queijo - R$ 32,90 ");
        chkBatata6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBatata6ActionPerformed(evt);
            }
        });

        chkBatata7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBatata7.setForeground(new java.awt.Color(0, 0, 0));
        chkBatata7.setText("Batata Recheada de Lombo com Catupiry - R$ 32,90 ");
        chkBatata7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBatata7ActionPerformed(evt);
            }
        });

        chkBebida3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBebida3.setForeground(new java.awt.Color(0, 0, 0));
        chkBebida3.setText("Coca Cola 350 ml - R$ 7,00");
        chkBebida3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBebida3ActionPerformed(evt);
            }
        });

        chkBebida1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBebida1.setForeground(new java.awt.Color(0, 0, 0));
        chkBebida1.setText("Fruki 350 ml - R$ 6,00");
        chkBebida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBebida1ActionPerformed(evt);
            }
        });

        chkBebida2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBebida2.setForeground(new java.awt.Color(0, 0, 0));
        chkBebida2.setText("Coca Cola Zero Açucar 350 ml - R$ 7,00");
        chkBebida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBebida2ActionPerformed(evt);
            }
        });

        chkBebida4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBebida4.setForeground(new java.awt.Color(0, 0, 0));
        chkBebida4.setText("Fruki Zero Açucar 350 ml - R$ 6,00");
        chkBebida4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBebida4ActionPerformed(evt);
            }
        });

        chkBebida5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBebida5.setForeground(new java.awt.Color(0, 0, 0));
        chkBebida5.setText("Água Mineral 600 ml - R$ 4,00");
        chkBebida5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBebida5ActionPerformed(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(102, 51, 0));
        jTextField3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(204, 153, 0));
        jTextField3.setText("RAIZ ESPECIAIS");

        jTextField4.setBackground(new java.awt.Color(102, 51, 0));
        jTextField4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(204, 153, 0));
        jTextField4.setText("RAIZ FITNESS");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setBackground(new java.awt.Color(102, 51, 0));
        jTextField5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(204, 153, 0));
        jTextField5.setText("RAIZ DOCE");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        chkBatata9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBatata9.setForeground(new java.awt.Color(0, 0, 0));
        chkBatata9.setText("Batata Doce Recheada de Frango Desfiado e Requeijão Light- R$ 29,90 ");
        chkBatata9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBatata9ActionPerformed(evt);
            }
        });

        chkBatata10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBatata10.setForeground(new java.awt.Color(0, 0, 0));
        chkBatata10.setText("Batata Doce Recheada de Cogumelos e Creme de Ricota Light  - R$ 29,90 ");
        chkBatata10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBatata10ActionPerformed(evt);
            }
        });

        chkBatata8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBatata8.setForeground(new java.awt.Color(0, 0, 0));
        chkBatata8.setText("Batata Doce Recheada de Carne e Brócolis  - R$ 32,90 ");
        chkBatata8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBatata8ActionPerformed(evt);
            }
        });

        chkBatata11.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBatata11.setForeground(new java.awt.Color(0, 0, 0));
        chkBatata11.setText("Batata Doce Recheada de Banana e Canela  - R$ 25,90 ");
        chkBatata11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBatata11ActionPerformed(evt);
            }
        });

        chkBatata12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBatata12.setForeground(new java.awt.Color(0, 0, 0));
        chkBatata12.setText("Batata Doce Recheada Cacau e Pasta de Amendoim  - R$ 29,90 ");
        chkBatata12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBatata12ActionPerformed(evt);
            }
        });

        chkBatata14.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBatata14.setForeground(new java.awt.Color(0, 0, 0));
        chkBatata14.setText("Batata Doce Recheada Doce de Leite e Coco  - R$ 29,90 ");
        chkBatata14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBatata14ActionPerformed(evt);
            }
        });

        chkBatata13.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBatata13.setForeground(new java.awt.Color(0, 0, 0));
        chkBatata13.setText("Batata Doce Recheada Chocolate com Avelã  - R$ 29,90 ");
        chkBatata13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBatata13ActionPerformed(evt);
            }
        });

        jTextField6.setBackground(new java.awt.Color(102, 51, 0));
        jTextField6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(204, 153, 0));
        jTextField6.setText("BEBIDAS");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        chkBebida6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        chkBebida6.setForeground(new java.awt.Color(0, 0, 0));
        chkBebida6.setText("Monster Zero Açucar 453 ml - R$ 12,00");
        chkBebida6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBebida6ActionPerformed(evt);
            }
        });

        jTextField7.setBackground(new java.awt.Color(255, 204, 153));
        jTextField7.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(102, 51, 0));
        jTextField7.setText("MENU");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 51, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(102, 51, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(102, 51, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(102, 51, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(89, 62, 36));
        jPanel7.setForeground(new java.awt.Color(153, 102, 0));

        jPanel8.setBackground(new java.awt.Color(255, 204, 153));

        btnPedido.setBackground(new java.awt.Color(102, 51, 0));
        btnPedido.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnPedido.setText("PEDIDOS");
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(102, 51, 0));
        btnLimpar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setText("VALOR TOTAL:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(lblTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedido)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addComponent(lblTotal)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkBatata7)
                                    .addComponent(chkBatata5)
                                    .addComponent(chkBatata9)
                                    .addComponent(chkBatata10)
                                    .addComponent(chkBatata2)
                                    .addComponent(chkBatata6)
                                    .addComponent(chkBatata3)
                                    .addComponent(chkBatata4)
                                    .addComponent(chkBatata1)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkBatata8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(337, 337, 337)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(chkBatata11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(276, 276, 276)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chkBebida2))
                                    .addComponent(chkBebida3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkBebida6)
                                    .addComponent(chkBebida5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkBatata14)
                                    .addComponent(chkBatata13)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(chkBebida1)
                                        .addGap(114, 114, 114)
                                        .addComponent(chkBebida4))
                                    .addComponent(chkBatata12)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkBatata1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkBatata2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkBatata3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkBatata4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkBatata5)
                        .addGap(4, 4, 4)
                        .addComponent(chkBatata6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkBatata7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkBatata11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkBatata12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkBatata13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkBatata14)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(chkBatata8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkBatata9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkBatata10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkBebida1)
                            .addComponent(chkBebida4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkBebida2)
                            .addComponent(chkBebida5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkBebida3)
                            .addComponent(chkBebida6))))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void chkBebida1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void chkBebida3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void chkBatata7ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void chkBatata6ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void chkBatata5ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void chkBatata3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void chkBatata4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void chkBatata2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void chkBatata1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void chkBebida2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void chkBebida4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void chkBebida5ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void chkBatata9ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void chkBatata10ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void chkBatata8ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void chkBatata11ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void chkBatata12ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void chkBatata14ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void chkBatata13ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void chkBebida6ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {                                          
        double total = 0; // começa o total com 0
        //verifica item por item e soma os valores marcados
        if (chkBatata1.isSelected()) total += 29.90; //Se a batata estiver
        // seleciona, soma 29,90
        if(chkBatata2.isSelected()) total += 27.90;
        if(chkBatata3.isSelected()) total += 32.90;
        if(chkBatata4.isSelected()) total += 32.90;
        if(chkBatata5.isSelected()) total += 32.90;
        if(chkBatata6.isSelected()) total += 32.90;
        if(chkBatata7.isSelected()) total += 32.90;
        if(chkBatata8.isSelected()) total += 32.90;
        if(chkBatata9.isSelected()) total += 29.90;
        if(chkBatata10.isSelected()) total += 29.90;
        if(chkBatata11.isSelected()) total += 25.90;
        if(chkBatata12.isSelected()) total += 29.90;
        if(chkBatata13.isSelected()) total += 29.90;
        if(chkBatata14.isSelected()) total += 29.90;
        if(chkBebida1.isSelected()) total += 6;
        if(chkBebida2.isSelected()) total += 7;
        if(chkBebida3.isSelected()) total += 7;
        if(chkBebida4.isSelected()) total += 6;
        if(chkBebida5.isSelected()) total += 4;
        if(chkBebida6.isSelected()) total += 12;
        
        // Mostra o resultado formatada
        lblTotal.setText(String.format("Total: R$ %.2f", total));
        // Trocar a cor e mensagem conforme o valor
        if(total== 0){
            lblTotal.setForeground(new java.awt.Color(200,0,0));
            lblTotal.setText("Nenhum item selecionado!");
        }
        else if(total < 10){
            lblTotal.setForeground(new java.awt.Color(0,100,0));
        }
        else if(total <=25){
            lblTotal.setForeground(new java.awt.Color(0,128,255));
        }
        else{
            lblTotal.setForeground(new java.awt.Color(0,128,9));
            lblTotal.setText(String.format("Pedido completo! Total: R$%.2f", total));
        }
    }                                         

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // Desmarca todas as opções
        chkBatata1.setSelected(false);
        chkBatata2.setSelected(false);
        chkBatata3.setSelected(false);
        chkBatata4.setSelected(false);
        chkBatata5.setSelected(false);
        chkBatata6.setSelected(false);
        chkBatata7.setSelected(false);
        chkBatata8.setSelected(false);
        chkBatata9.setSelected(false);
        chkBatata10.setSelected(false);
        chkBatata11.setSelected(false);
        chkBatata12.setSelected(false);
        chkBatata13.setSelected(false);
        chkBatata14.setSelected(false);
        chkBebida1.setSelected(false);
        chkBebida2.setSelected(false);
        chkBebida3.setSelected(false);
        chkBebida4.setSelected(false);
        chkBebida5.setSelected(false);
        chkBebida6.setSelected(false);
        // Restaura o texto do resultado
        lblTotal.setText("Total: R$ 0.00");
        lblTotal.setForeground(new java.awt.Color(0,0,0));
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lanchonete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lanchonete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lanchonete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lanchonete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lanchonete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPedido;
    private javax.swing.JCheckBox chkBatata1;
    private javax.swing.JCheckBox chkBatata10;
    private javax.swing.JCheckBox chkBatata11;
    private javax.swing.JCheckBox chkBatata12;
    private javax.swing.JCheckBox chkBatata13;
    private javax.swing.JCheckBox chkBatata14;
    private javax.swing.JCheckBox chkBatata2;
    private javax.swing.JCheckBox chkBatata3;
    private javax.swing.JCheckBox chkBatata4;
    private javax.swing.JCheckBox chkBatata5;
    private javax.swing.JCheckBox chkBatata6;
    private javax.swing.JCheckBox chkBatata7;
    private javax.swing.JCheckBox chkBatata8;
    private javax.swing.JCheckBox chkBatata9;
    private javax.swing.JCheckBox chkBebida1;
    private javax.swing.JCheckBox chkBebida2;
    private javax.swing.JCheckBox chkBebida3;
    private javax.swing.JCheckBox chkBebida4;
    private javax.swing.JCheckBox chkBebida5;
    private javax.swing.JCheckBox chkBebida6;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration                   
}
