/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversormoedas;

/**
 *
 * @author JIANLUCAPALINI
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        boxEscolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
        "USD - Dólar Americano",
        "EUR - Euro",
        "GBP - Libra",
        "RUB - Rublo Russo",
        "JPY - Iene"
    }));
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnConverter = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        boxEscolha = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("CONVERSOR DE MOEDAS");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setText("Reais R$:");

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        btnConverter.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnConverter.setForeground(new java.awt.Color(255, 0, 0));
        btnConverter.setText("Converter");
        btnConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConverterActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 0, 0));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(255, 102, 0));
        lblResultado.setText("Valor Convertido");

        boxEscolha.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        boxEscolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "GBP", "RUB", "JPY" }));
        boxEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxEscolhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnConverter)
                        .addGap(92, 92, 92)
                        .addComponent(btnLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(lblResultado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(boxEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(boxEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConverter)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addComponent(lblResultado)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {                                         
  
    }                                        

    private void btnConverterActionPerformed(java.awt.event.ActionEvent evt) {                                             
      
String valorStr = txtValor.getText().trim().replace(",", ".");



if (valorStr.isEmpty()) {
    lblResultado.setText("Campo vazio! Digite um valor.");
} else {
    try {
        double valor = Double.parseDouble(valorStr);

        if (valor > 0) {
            
            String moeda = (String) boxEscolha.getSelectedItem();
            double resultado = 0;
            double taxa = 0;
            double taxaExtra = 0;
            String simbolo = "";

            if (moeda.equals("USD - Dólar Americano")) {
                taxa = 5.40;
                taxaExtra = 0.01;
                resultado = (valor / taxa) * (1 + taxaExtra);
                simbolo = "USD $";
            } else if (moeda.equals("EUR - Euro")) {
                taxa = 6.28;
                taxaExtra = 0.01;
                resultado = (valor / taxa) * (1 + taxaExtra);
                simbolo = "Euro €";
            } else if (moeda.equals("GBP - Libra")) {
                taxa = 7.22;
                taxaExtra = 0.03;
                resultado = (valor / taxa) * (1 + taxaExtra);
                simbolo = "Libra £";
            } else if (moeda.equals("RUB - Rublo Russo")) {
                taxa = 0.06;
                taxaExtra = 0.01;
                resultado = (valor * taxa) * (1 + taxaExtra);
                simbolo = "Rublo ₽";
            } else if (moeda.equals("JPY - Iene")) {
                taxa = 0.03;
                taxaExtra = 0.02;
                resultado = (valor * taxa) * (1 + taxaExtra);
                simbolo = "Iene ¥";
            } else {
                lblResultado.setText("Moeda não reconhecida.");
                return;
            }
            lblResultado.setText(String.format("%s %.2f", simbolo, resultado));
        } else {
            lblResultado.setText("Por favor informe um valor maior que zero!");
        }
    } catch (NumberFormatException e) {
        lblResultado.setText("Valor inválido! Digite apenas números.");
    }
}
            
    }                                            

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {                                          
        txtValor.setText("");
        lblResultado.setText("");
        lblResultado.setForeground(new java.awt.Color(0,0,0));
        txtValor.requestFocus();
    }                                         

    private void boxEscolhaActionPerformed(java.awt.event.ActionEvent evt) {                                           

    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> boxEscolha;
    private javax.swing.JButton btnConverter;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtValor;
    // End of variables declaration                   
}
